[[plugins]]
repo = 'Shougo/dein.vim'

# [[plugins]]
# repo = 'Shougo/neosnippet.vim'
#
# [[plugins]]
# repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

# [[plugins]]
# repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'tpope/vim-surround'

# Stop tagbar for now, since it causes annoying bugs
# [[plugins]]
# repo = 'majutsushi/tagbar'

[[plugins]]
repo = 't9md/vim-textmanip'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'thinca/vim-splash'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'eiji03aero/quick-notes'

# [[plugins]]
# repo = 'liuchengxu/vim-clap'

# ==================== File explorer ====================
[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'francoiscabrol/ranger.vim'
