# ==================== javascript ====================
# [[plugins]]
# repo = 'pangloss/vim-javascript'
# on_ft = ['javascript', 'typescript', 'vue']

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript', 'typescript']

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = ['graphql']

[[plugins]]
repo = 'elmcast/elm-vim'
on_ft = ['elm']

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

[[plugins]]
repo = 'leafOfTree/vim-vue-plugin'
on_ft = ['vue']

[[plugins]]
repo = 'prettier/vim-prettier'
on_ft = ['javascript', 'typescript', 'css', 'scss', 'json', 'graphql', 'markdown', 'vue', 'yaml', 'html']

# ==================== dart ====================
[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft = ['dart']

# [[plugins]]
# repo = 'reisub0/hot-reload.vim' # hot-reload for flutter
# on_ft = ['dart']

# ==================== html ====================
[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = ['pug', 'vue']

[[plugins]]
repo = 'lepture/vim-jinja'
on_ft = ['html', 'jinja2', 'jinja', 'njk']

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css', 'scss']

[[plugins]]
repo = 'wavded/vim-stylus'
on_ft = ['stylus']

# ==================== haskell ====================
[[plugins]]
repo = 'dag/vim2hs'
on_ft = ['haskell']
hook_source = '''
hi hsConceal ctermfg=214
hi hsOperator ctermfg=214
'''

# ==================== cpp ====================
# repo = 'justmao945/vim-clang'
# on_ft = ['c', 'cpp', 'h', 'hpp']

repo = 'octol/vim-cpp-enhanced-highlight'
on_ft = ['cpp', 'h', 'hpp']

# ==================== go ====================
# [[plugins]]
# repo = 'fatih/vim-go'
# on_ft = ['go']

[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = ['go']

# ==================== python ====================
[[plugins]]
repo = 'hdima/python-syntax'
on_ft = ['javascript']

# ==================== kotlin ====================
[[plugins]]
repo = 'udalov/kotlin-vim'
on_ft = ['kotlin']

# ==================== sql ====================
[[plugins]]
repo = 'vim-scripts/dbext.vim'
on_ft = ['sql']

# ==================== config file ====================
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'uarun/vim-protobuf'
on_ft = ['proto']
