# ==================== deoplete ====================
[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("python3")'
depends = ['roxma/nvim-yarpc', 'roxma/vim-hug-neovim-rpc']
on_i = 1

[[plugins]]
repo = 'roxma/nvim-yarp'
if = ''' ! has('nvim') '''

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = ''' ! has('nvim') '''

# [[plugins]]
# repo = 'zchee/deoplete-go'
# on_ft= ['go']
