alias ls='ls -G'

alias vimrc='vim ~/.vimrc'
alias authc='cd auth-conciergeu'
alias dia='cd dialog_api'
alias cuw='cd cu_webplugin'
alias lenga='cd lenga_app'

alias gis='git status'
alias girh='git reset --hard'
alias gilg='git log --graph'
alias gilgp='git log --graph -p'
alias gilgo='git log --graph --oneline'
alias gia='git add .'
alias gicm='git commit -m'
alias gicma='git commit --amend --no-edit'
alias gicm-base='git commit --allow-empty -m "base commit"'
alias gib='git branch'
alias gibd='git branch -D'
alias gim='git merge'
alias giplr='git pull --rebase origin master'
alias giplom='git pull origin master'
alias girbc='git rebase --continue'
alias gicl='git clone'
alias gicurb='git_current_branch'

alias tm='tmux new-session'
alias tmls='tmux ls'
alias tma='tmux a -t'
alias tmn='tmux new -s'
alias tmkss='tmux kill-session -t'
alias tmksr='tmux kill-server'
alias tmslmv='tmux split-window -h & tmux resize-pane -R 40'
alias tmr='tmuxinator'

alias dk='docker'
alias dkc='docker container'
alias dki='docker image'
alias dkce='docker container exec -it'
alias dkcom='docker-compose'
alias dkcom-e='docker-compose -f .eiji03aero.local.docker-compose.yml'
alias dkcom-econ='docker-compose -f docker-compose1.0.yml  -f .eiji03aero.local.docker-compose1.0.yml'
alias dkv='docker volume'

alias vg='vagrant'
