alias ls='ls -G'

alias gis='git status'
alias gif='git fetch'
alias girh='git reset --hard'
alias gilg='git log --graph'
alias gilgp='git log --graph -p'
alias gilgo='git log --graph --oneline'
alias gia='git add .'
alias gicm='git commit -m'
alias gicmn='git commit -n -m'
alias gicma='git commit --amend --no-edit'
alias gicm-base='git commit --allow-empty -m "base commit"'
alias gib='git branch'
alias gicl='git clone'

alias tm='tmux new-session'
alias tmls='tmux ls'
alias tma='tmux a -t'
alias tmn='tmux new -s'
alias tmkss='tmux kill-session -t'
alias tmksr='tmux kill-server'
alias tmr='tmuxinator'

alias dk='docker'
alias dkc='docker container'
alias dki='docker image'
alias dkcom='docker-compose'
alias dkcom-e='docker-compose -f .eiji03aero.local.docker-compose.yml'
alias dkv='docker volume'
