alias ls='ls -G'

alias vimrc='vim ~/.vimrc'
alias authc='cd auth-conciergeu'
alias dia='cd dialog_api'
alias cuw='cd cu_webplugin'
alias lenga='cd lenga_app'

alias gis='git status'
alias girh='git reset --hard'
alias gilg='git log --graph'
alias gilgp='git log --graph -p'
alias gilgo='git log --graph --oneline'
alias gia='git add .'
alias gicm='git commit -m'
alias gica='git commit --amend --no-edit'
alias gib='git branch'
alias gic='git checkout'
alias gim='git merge'
alias giplr='git pull --rebase origin master'
alias giplom='git pull origin master'
alias girbc='git rebase --continue'

alias tm='tmux new-session'
alias tmls='tmux ls'
alias tma='tmux a -t'
alias tmn='tmux new -s'
alias tmkss='tmux kill-session -t'
alias tmksr='tmux kill-server'
alias tmslmv='tmux split-window -h & tmux resize-pane -R 40'
alias tmr='tmuxinator'

alias dkc='docker container'
alias dkce='docker container exec -it'

alias vg='vagrant'
