let g:airline_theme                             = 'jellybeans'
" let g:airline_theme                             = 'term'
let g:airline_powerline_fonts                   = 0
let g:airline#extensions#tabline#enabled        = 1
let g:airline#extensions#bufferline#enabled     = 0
let g:airline#extensions#tabline#buffer_nr_show = 1
let g:airline#extensions#whitespace#enabled     = 0
let g:airline#extensions#whitespace#symbol      = '!'
let g:airline#extensions#branch#enabled         = 1
let g:airline_branch_prefix                     = '⭠ '
let g:airline#extensions#readonly#symbol        = '⭤ '
let g:airline#extensions#branch#enabled         = 1
let g:airline#extensions#readonly#enabled       = 1
