FROM ruby:2.7.1-buster

ENV LANG C.UTF-8

RUN apt-get update \
  && apt-get upgrade -q --no-install-recommends -y \
  && apt-get install -q --no-install-recommends -y \
    build-essential \
    nodejs

RUN mkdir /app
WORKDIR /app

RUN git config --global user.email "eiji03aero@gmail.com" \
  && git config --global user.name "eiji03aero"

RUN gem install rails
