FROM node:8.12.0-stretch

WORKDIR /app

ENV YARN_VERSION 1.16.0

RUN apt-get update && apt-get upgrade -y

RUN curl -fSLO --compressed "https://yarnpkg.com/downloads/$YARN_VERSION/yarn-v$YARN_VERSION.tar.gz" \
    && tar -xzf yarn-v$YARN_VERSION.tar.gz -C /opt/ \
    && ln -snf /opt/yarn-v$YARN_VERSION/bin/yarn /usr/local/bin/yarn \
    && ln -snf /opt/yarn-v$YARN_VERSION/bin/yarnpkg /usr/local/bin/yarnpkg \
    && rm yarn-v$YARN_VERSION.tar.gz

RUN git config --global user.email "eiji03aero@gmail.com" \
  && git config --global user.name "eiji03aero"
