#!/bin/bash
COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

branchName=$(git rev-parse --abbrev-ref HEAD)
ticketId=$(echo $branchName | grep -o '^[0-9]*')
firstLine=$(head -n1 $1)

# If first line is empty, treat it as not --amend one
if [ -z "$firstLine" -a -n "$ticketId" ] ;then
    sed -i "" "1 s/^/[#${ticketId}] /" $1
fi
